# Generated by Django 4.1.2 on 2022-10-23 15:13

from django.db import migrations, models
import django.db.models.deletion
import form_demos2.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(validators=[form_demos2.web.validators.ValueInRangeValidator(1, 25)]),
        ),
        migrations.AddField(
            model_name='todo',
            name='assignee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='web.person'),
            preserve_default=False,
        ),
    ]
